- name: ğŸ“¢ Send Telegram Notification
  uses: appleboy/telegram-action@master
  with:
    to: ${{ vars.TELEGRAM_CHAT_ID }}  # å¿…é¡»ç”¨vars.å‰ç¼€å¼•ç”¨ç¯å¢ƒå˜é‡
    token: ${{ vars.TELEGRAM_TOKEN }}
    message: "å¤©ç¿¼ç½‘ç›˜ç­¾åˆ°ç»“æœï¼š${{ job.status }}"
